name: CI/CD Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Run unit tests
        run: |
          PYTHONPATH=backend pytest backend/tests -v


  build:
    name: Build and Push Docker Image
    runs-on: self-hosted
    environment: test
    needs: unit-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            codeykenny/github-actions-learn-2:latest
            codeykenny/github-actions-learn-2:${{ github.sha }}
            codeykenny/github-actions-learn-2:${{ github.run_number }}


  deploy:
    name: Deploy Application
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: |
          docker compose down
          docker compose up -d --build

